---

- hosts: all
  become: true
  tasks:

  - name: Install curl
    apt:
      name: curl
      state: present
      update_cache: yes
  
  - name: Install Software properties common i.e add-apt-repository
    apt:
      name: software-properties-common
      state: present
      update_cache: yes

  - name: Add the GPG key for the official Docker repository
    shell:
      cmd: "curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -"
  
  - name: Add the Docker repository to APT sources
    shell:
      cmd: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"'
  
  - name: Install Docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes

- hosts: jenkins
  become: true
  tasks:
  
  - name: Install Java 11 JDK
    apt:
      name: openjdk-11-jdk
      state: present
      update_cache: yes

  - name: Install Java 11 JRE
    apt:
      name: openjdk-11-jre
      state: present
      update_cache: yes
  
  - name: Add Jenkins repository GPG keys
    shell:
      cmd: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null"


  - name: Add Jenkins repository to the sources list
    shell:
      cmd: "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null"
    
  - name: Install Jenkins
    apt:
      name: jenkins
      state: present
      update_cache: yes
 
  - name: Install Maven
    apt: 
      name: maven
      state: present
      update_cache: yes

- hosts: dockerhosts
  become: true
  tasks:

  - name: Install docker-compose
    shell:
      cmd: "curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose"
  
  - name: Set permissions for docker-compose  
    file:
      path: /usr/local/bin/docker-compose
      mode: a+x